name: di_kit
description: Dependency injection mechanism.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  get_it: ^8.0.3
  barrel_files_annotation:
  
dev_dependencies:
  linter_analysis:
  barrel_files: 
  build_runner:
