name: foundation_kit
description: Foundation components
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  barrel_files_annotation:

dev_dependencies:
  linter_analysis:
  barrel_files: 
  build_runner:
